__APP_DIR__/logs/access.log {
    monthly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat -%Y-%m
    postrotate
        docker kill --signal USR1 __APP_NAME__ 2>/dev/null || true
    endscript
}
